### ISSUE TITLE
Heroku エラーコードH10の解決

### ISSUE THREAD

**Issue by KazukiOtomo** [KazukiOtomo/Circlejudgebackend#34]

**Comment by OHMORIYUSUKE** [comment]
## 提案

バグ修正のために、毎回デプロイするのはbuildで、herokuの無料枠を使い切る可能性があるので、[アプリのローカルでの実行](https://devcenter.heroku.com/ja/articles/heroku-local)しませんか。

**Comment by OHMORIYUSUKE** [comment]
## (原因が分からなくて)悔しくて死にそうです！
<img src="https://tavola-world.up.seesaa.net/image/Sound-Euphonium-2019.06.01-new.gif" width="500">

**Comment by KazukiOtomo** [comment]
とりあえずHeroku CLIをアップデート中...
