### ISSUE TITLE
`/question/answer`に不正な`question_id`が指定されたときに`insert`される

### ISSUE THREAD

**Issue by OHMORIYUSUKE** [KazukiOtomo/Circlejudgebackend#59]
## `/question/answer`に不正な`question_id`が指定されたときに`insert`される

不正な`question_id`が`insert`されてしまうと、`/result`をたたいた時に500エラーになる。

## 提案

`/question/answer`に不正な`question_id`が指定されたときに、`{'message': 'ERROR'}`にする。

**Comment by KazukiOtomo** [comment]
他のSQLのSELECT実行に失敗したときも同様なので、DAOでメソッドに切り出すのが良さそう
